#{'state': 'ok', 'message': '', 'special': '', 'vipMessage': '', 'isLogin': 0, 'data': {'viewtotal': '1', 'items':
    # [{'content': '<div class="vT_detail_content w760c"> \n <p>\u3000\u3000广西德胜工程造价咨询有限公司受柳州市国土资源局的委托，就“河东综合服务大楼会议室音视频系统设备采购、集成项目及项目监理服务”项目（项目编号：LZG15-331）组织采购，评标工作已经结束，中标结果如下：</p>\n <p></p>\n <p>&nbsp;</p>\n <p><strong>一、项目信息</strong></p>\n <p>项目编号：LZG15-331</p>\n <p>项目名称：河东综合服务大楼会议室音视频系统设备采购、集成项目及项目监理服务</p>\n <p>项目联系人：敬伟 </p>\n <p>联系方式：0772-8857228</p>\n <p>&nbsp;</p>\n <p><strong>二、采购人信息</strong></p>\n <p>采购人名称：柳州市国土资源局</p>\n <p>采购人地址：广西柳州市立新路49号</p>\n <p>采购人联系方式：罗雪峰、联系电话：0772-2837737</p>\n <p>&nbsp;</p>\n <p><strong>三、项目用途、简要技术要求及合同履行日期：</strong></p>\n <p></p>\n <p>详见招标文件招标项目采购需求</p>\n <p></p>\n <p>&nbsp;</p>\n <p></p>\n <p><strong>四、采购代理机构信息</strong></p>\n <p>采购代理机构全称：广西德胜工程造价咨询有限公司</p>\n <p>采购代理机构地址：广西柳州市三中路92号原地区政法委办公楼</p>\n <p>采购代理机构联系方式：敬伟、联系电话：0772-8857228 8857258</p>\n <p>&nbsp;</p>\n <p><strong>五、中标信息</strong></p>\n <p>招标公告日期：2015年08月12日</p>\n <p>中标日期：2015年09月02日</p>\n <p>总中标金额：\n  <fmt:formatnumber type="currency" pattern="￥.000000#">\n   448.4\n  </fmt:formatnumber> 万元（人民币）</p>\n <p>中标供应商名称、联系地址及中标金额：</p>\n <p></p>\n <table border="1" cellpadding="0" cellspacing="0"> \n  <tbody> \n   <tr> \n    <td>序号</td> \n    <td>中标供应商名称</td> \n    <td>中标供应商联系地址</td> \n    <td>中标金额(万元)</td> \n   </tr> \n   <tr> \n    <td>1</td> \n    <td>（001分标）浪潮集团有限公司</td> \n    <td>济南市高新区浪潮路1036号</td> \n    <td>431.0</td> \n   </tr> \n   <tr> \n    <td>2</td> \n    <td>（002分标）广西联信科技顾问有限责任公司</td> \n    <td>南宁市振华路3号青工宿舍A406号房</td> \n    <td>17.4</td> \n   </tr> \n  </tbody>\n </table>\n <p></p>\n <p>&nbsp;</p>\n <p>评标委员会成员名单：</p>\n <p>谢洪、范建新、温华、邹冬萍、顾娟、吴兴标、张宇翔</p>\n <p>&nbsp;</p>\n <p>中标标的名称、规格型号、数量、单价、服务要求：</p>\n <p></p>\n <p>001分标：相关音视频系统设备采购及集成；002分标：项目监理服务1项</p>\n <p></p>\n <p>&nbsp;</p>\n <p><strong>六、其它补充事宜</strong></p>\n <p></p>\n <p style="text-justify: inter-ideograph; text-align: justify; line-height: 18pt; text-indent: 28pt">1、投标人对中标公告有异议的，在中标公告发布之日起七个工作日内，以书面形式向采购人或采购代理机构提出质疑。</p>\n <p style="line-height: 18pt; text-indent: 28pt">2、质疑人必须按《广西壮族自治区政府采购供应商质疑处理办法（桂财采〔2006〕11号文）的规定和招标文件“投标人须知”第一条第（九）款的要求来进行质疑，如不按政府采购相关规定质疑的，视为无效质疑，不予受理。</p>\n <p style="line-height: 22.5pt; margin: 0cm 21pt 0pt 0cm">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;广西德胜工程造价咨询有限公司</p>\n <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;二〇一五年九月七日</p>\n <p></p> \n <p>&nbsp;</p> \n <p></p> \n <p></p> \n <p></p> \n <p></p> \n <p>&nbsp;</p> \n <p></p> \n</div>',
    #  'createTime': '1464746329000', 'title': '柳州市国土资源局河东综合服务大楼会议室音视频系统设备采购、集成项目及项目监理服务中标公告',
    #  'abs': '<div class="table">\n <h5>公告概要：</h5>\n <table width="600" border="0" cellspacing="1" bgcolor="#bfbfbf" style="text-align:left;">\n  <tbody>\n   <tr>\n    <td colspan="4"><b>公告信息：</b></td>\n   </tr>\n   <tr>\n    <td class="title" width="128">采购项目名称</td>\n    <td colspan="3" width="430">河东综合服务大楼会议室音视频系统设备采购、集成项目及项目监理服务</td>\n   </tr>\n   <tr>\n    <td class="title">品目</td>\n    <td colspan="3"><p>货物/其他货物/其他不另分类的物品</p></td>\n   </tr>\n   <tr>\n    <td class="title">采购人</td>\n    <td colspan="3">柳州市国土资源局</td>\n   </tr>\n   <tr>\n    <td class="title">行政区域</td>\n    <td width="168">柳州市</td>\n    <td class="title" width="128">公告时间</td>\n    <td width="168">2015年09月07日 08:28</td>\n   </tr>\n   <tr>\n    <td class="title">本项目招标公告日期</td>\n    <td width="168">2015年08月12日</td>\n    <td class="title" width="128">定标日期</td>\n    <td width="168">2015年09月02日</td>\n   </tr>\n   <tr>\n    <td class="title">评标委员会成员名单</td>\n    <td colspan="3">谢洪、范建新、温华、邹冬萍、顾娟、吴兴标、张宇翔</td>\n   </tr>\n   <tr>\n    <td class="title">总中标金额</td>\n    <td colspan="3">￥448.4 万元（人民币）</td>\n   </tr>\n   <tr>\n    <td colspan="4"><b>联系人及联系方式：</b></td>\n   </tr>\n   <tr>\n    <td class="title">项目联系人</td>\n    <td colspan="3">敬伟 </td>\n   </tr>\n   <tr>\n    <td class="title">项目联系电话</td>\n    <td colspan="3">0772-8857228</td>\n   </tr>\n   <tr>\n    <td class="title" width="128">采购人</td>\n    <td width="430" colspan="3">柳州市国土资源局</td>\n   </tr>\n   <tr>\n    <td class="title">采购人地址</td>\n    <td colspan="3">广西柳州市立新路49号</td>\n   </tr>\n   <tr>\n    <td class="title">采购人联系方式</td>\n    <td colspan="3">罗雪峰、联系电话：0772-2837737</td>\n   </tr>\n   <tr>\n    <td class="title">代理机构名称</td>\n    <td colspan="3">广西德胜工程造价咨询有限公司</td>\n   </tr>\n   <tr>\n    <td class="title">代理机构地址</td>\n    <td colspan="3">广西柳州市三中路92号原地区政法委办公楼</td>\n   </tr>\n   <tr>\n    <td class="title">代理机构联系方式</td>\n    <td colspan="3">敬伟、联系电话：0772-8857228 8857258</td>\n   </tr>\n  </tbody>\n </table>\n</div>', 'purchaser': '柳州市国土资源局', 'publishTime': '1441585712000', 'updateTime': '1464746329000', 'proxy': '广西德胜工程造价咨询有限公司', 'link': 'http://www.ccgp.gov.cn/cggg/dfgg/zbgg/201509/t20150907_5811339.htm', 'pid': '244751', 'uuid': '407bde28419b11e6a050288023a1a420', 'intro': '广西德胜工程造价咨询有限公司受柳州市国土资源局的委托，就“河东综合服务大楼会议室音视频系统设备采购、集成项目及项目监理服务”项目（项目编号：LZG15-331）组织采购，评标工作已经结束，中标结果如：一、项目'}], 'pageSize': '100'}}

# <table id="CWL_BIDDING" name="招投标">
# 						<column id="ID" primaryKey="true" required="true" type="varchar(30)"   name="ID"/>
# 						<column id="CDATE"  type="varchar(8)"  name="发布时间" />
# 						<column id="TITLE"  type="varchar(256)" name="标题"/>
# 						<column id="CONTEXT" type="TEXT" name="内容" />
# 						<column id="PURCHASER" type="varchar(32)" name="采购人" />
# 						<column	id="COM_ID"   required="true" type="varchar(30)"  name="所属企业ID"/>
# 					</table>
import com.inspur.reptile.skyeyes.common.DateTool as DateTool
from com.inspur.reptile.skyeyes.domain.Entity import Entity
import pymysql

class BidEntity(Entity):
    map={"ID":'uuid',
         "CDATE":'createTime',
         "TITLE":'title',
         "PURCHASER":'purchaser',
         "COM_ID":'comid',
         "CONTEXT":'content'}
    tableName="CWL_BIDDING"
    def __init__(self,dataStr={},resource=None):
        dataStr['createTime']=DateTool.transDataFormat(dataStr['createTime'],"%Y%m%d")
        #dataStr["content"]=pymysql.escape_string(dataStr["content"])
        self.dataStr=dataStr
        super().__init__(resource)